- name: "Setup wordpress"
  hosts: "{{ server | default('personal') }}"
  remote_user: "{{ default_user }}"

  tasks:
    # Abstracting out versions for updating this later.
    # default_user is not a documented variable. But you could use this to change the name of the deployer user.
    - name: Set versions and other defaults
      ansible.builtin.set_fact:
        requires_become: "{{ (default_user == 'root') | ternary('no', 'yes') }}"
        deploy_user: "{{ deploy_user | default('deployer') }}"
        php_version: "{{ php_version | default('7.4') }}"
        mariadb_version: "10.8.2"
        wordpress_deploy_path: "/home/{{ deploy_user | default('deployer') }}/wordpress-deploy"
        site_path: "/home/{{ deploy_user | default('deployer') }}/sites/{{ site_name }}"
        site_config_path: "/home/{{ deploy_user | default('deployer') }}/sites/{{ site_name }}/config"
        site_content_path: "/home/{{ deploy_user | default('deployer') }}/sites/{{ site_name }}/content"
      tags: ['tryout', 'tryout2']

    # We install tmux as a bonus to tinker with the server later if required
    # Feel free to do your theme development and other such work on this tmux session :)
    #
    - name: Install some basic packages for further installation
      apt:
        pkg:
          - apt-transport-https
          - curl
          - ca-certificates
          - tmux
        state: present
      become: "{{ requires_become }}"

    # sudo apt-key adv --fetch-keys 'https://mariadb.org/mariadb_release_signing_key.asc'
    - name: Fetch MariaDB repo keys
      ansible.builtin.apt_key:
        url: https://mariadb.org/mariadb_release_signing_key.asc
        state: present
      become: "{{ requires_become }}"

    # sudo add-apt-repository 'deb [arch=amd64,arm64] http://mariadb.mirror.globo.tech/repo/10.8.2/ubuntu/ focal main'
    - name: Add MariaDB repo
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64,arm64] http://mariadb.mirror.globo.tech/repo/{{mariadb_version}}/ubuntu focal main"
        state: present
      become: "{{ requires_become }}"

    # sudo add-apt-repository ppa:nginx/stable
    - name: "Add nginx repo"
      ansible.builtin.apt_repository:
        repo: "ppa:nginx/stable"
        state: present
      become: "{{ requires_become }}"

    - name: Update apt package cache and install packages
      apt:
        pkg:
          - "nginx"
          - "ghostscript"
          - "php{{ php_version }}"
          - "php{{ php_version }}-fpm"
          - "php{{ php_version }}-common"
          - "php{{ php_version }}-curl"
          - "php{{ php_version }}-json"
          - "php{{ php_version }}-imagick"
          - "php{{ php_version }}-zip"
          - "php{{ php_version }}-mbstring"
          - "php{{ php_version }}-xml"
          - "php{{ php_version }}-bcmath"
          - "php{{ php_version }}-intl"
          - "php{{ php_version }}-xsl"
          - "php{{ php_version }}-mysql"
          - "mariadb-server"
        update_cache: yes
        state: present
      become: "{{ requires_become }}"

    - name: Download wp cli
      get_url:
        url: "https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar"
        dest: "/usr/local/bin/wp"
        mode: "u+rwx"
      become: "{{ requires_become }}"

    - name: Create a deployers user group
      group:
        name: deployers
        state: present
      become: "{{ requires_become }}"

    - name: Create deployer user
      user:
        name: deployer
        group: deployers
        state: present
      become: "{{ requires_become }}"

    - name: Create common config dir
      file:
        path: "{{ wordpress_deploy_path }}"
        state: directory
        recurse: yes
      become: yes
      become_user: "{{ deploy_user }}"

    - name: Create site content dir
      file:
        path: "{{ site_content_path }}"
        state: directory
        recurse: yes
        owner: "{{ deploy_user }}"
      become: yes
      become_user: "{{ deploy_user }}"
      tags: ['tryout2']

    - name: Create site config dir
      file:
        path: "{{ site_config_path }}"
        state: directory
        recurse: yes
        owner: "{{ deploy_user }}"
      become: yes
      become_user: "{{ deploy_user }}"
      tags: ['tryout2']

    - name: Create database password
      shell: "openssl rand -hex 6 > {{site_config_path}}/db-password"
      args:
        creates: "{{site_config_path}}/db-password"
      become_user: "{{ deploy_user }}"
      tags: ['tryout']

    - name: Read database password
      shell: "cat {{site_config_path}}/db-password"
      register: db_password_task
      tags: ['tryout']

    - name: Create database if does not exist
      shell: "mysql -e \"CREATE DATABASE IF NOT EXISTS {{ site_name }};\""
      become_user: "{{ deploy_user }}"
      tags: ['tryout']

    - name: Create database user if does not exist
      shell: "mysql -e \"CREATE USER IF NOT EXISTS '{{ site_name }}'@'localhost' IDENTIFIED BY '{{ db_password_task.stdout }}';\""
      become_user: "{{ deploy_user }}"
      tags: ['tryout']

    - name: Ensure database user has the right privileges to the site database
      shell: "mysql -e \"GRANT ALL PRIVILEGES ON {{ site_name }}.* TO '{{ site_name }}'@'localhost';\""
      become_user: "{{ deploy_user }}"
      tags: ['tryout']

# Following lines in /etc/php/7.4/fpm/pool.d/www.conf should be set to deploy_user and deployers group
# user = www-data
# group = www-data

# wp config create --dbname=mysite --dbuser=mysite --dbpass=`cat ../config/db-password` --locale=en_US
# download here
# wp core install --url=TEST --title="Hello World 123" --admin_user=admin --admin_password="TODO" --admin_email=anythign@example.com --skip-email


    # - name: Create database user
    #   community.mysql.mysql_user:
    #     name: "{{ lookup('password', site_config_path + '/mysql-user length=5 chars=ascii_letters') }}"
    #     password: "{{ lookup('password', site_config_path + '/mysql-password length=12 chars=ascii_letters') }}"
    #     priv: "{{ site_name }}.*:ALL,GRANT"
    #     host: localhost
    #     state: present
    #   become: "{{ requires_become }}"

    # - name: Create nginx config for the site

    # - name: Download wordpress
    #   cmd: "wp core download --locale=en_US --version={{ wordpress_version | default('latest') }}"

    # - name: Create a new database for site
    #   community.mysql.mysql_db:
    #     name: "{{ site_name }}"
    #     state: present
    #   become: "{{ requires_become }}"

    # - name: Generate wp-config using wp cli
    #   become: "{{ requires_become }}"

    # # TODO document site_title
    # # TODO document wordpress_admin_user
    # # TODO document wordpress_admin_email
    # # TODO notify_email should default to wordpress_admin_email
    # # TODO server notifications should be disabled only if notify_email is set to off
    # # TODO what about wordpress multi-site?
    # - name: Install wordpress
    #   cmd: "wp core install --url={{ domain }} --title={{ site_title | default('Hello World') }} --admin_user={{ wordpress_admin_user | default('admin') }} --admin_password={{ wordpress_admin_password }} --admin_email={{ wordpress_admin_email }}"

    # - name: Disable nginx sample config
    #   module: "File"
    #   args:
    #     name: "/etc/nginx/sites-enabled/default"
    #     state: "absent"
    #   require_root: true

    # - name: Add nginx config for the site
    #   todo:

    # - name: Reload nginx
    #   todo:

    # - name: Setup cron job for backups
    #   todo:

    # - name: Setup monit
    #   todo:

    # - name: Add mariadb config for monit
    #   todo:

    # - name: Add php-fpm config for monit
    #   todo:

    # - name: Add nginx config for monit
    #   todo:

    # - name: Disable systemd services
    #   todo:
    #   loop:
    #     - "nginx"
    #     - "php{{php_version}}-fpm"
    #     - "mariadb-server"

    # - name: Add site backup script
    #   todo:

    # - name: Add wordpress update notification script
    #   todo:

    # - name: Send post-install notification email
    #   todo:
