- name: Add site backup bash script
  ansible.builtin.template:
    src: "templates/backup-site.sh"
    dest: "{{ site_config_path }}/backup-site.sh"
    group: "www-data"
    owner: "www-data"
    mode: "0775"
  tags: ["install-scripts"]

- name: Add backup email script
  ansible.builtin.template:
    src: "templates/mail-backup.php"
    dest: "{{ site_config_path }}/mail-backup.php"
    group: "www-data"
    owner: "www-data"
    mode: "0775"
  tags: ["install-scripts"]

# Generate daily backups in the backup dir
- name: Setup daily backup cron
  ansible.builtin.cron:
    name: "generate {{ site_name }} backup"
    minute: "45"
    hour: "8"
    job: "bash {{site_config_path}}/backup-site.sh"
    user: "www-data"
  tags: ["install-scripts"]

# Every week mail the database backup to the user
- name: Setup cron to mail weekly backups
  ansible.builtin.cron:
    name: "mail weekly {{ site_name }} backup"
    minute: "0"
    hour: "9"
    weekday: "0"
    job: "php {{site_config_path}}/mail-backup.php"
    user: "www-data"
  tags: ["install-scripts"]

# Any backup older than 7 days will be deleted everyday
- name: Setup daily cron to delete backups older than 7 days
  ansible.builtin.cron:
    name: "clean {{ site_name }} backups"
    minute: "0"
    hour: "9"
    job: "find {{ site_backups_path }} -mtime +7 -exec echo {} \\;"
    user: "www-data"
  tags: ["install-scripts"]
